name: CI (Upgrade)

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  setupcheck:
    name: Setup Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  call-upgradesample-app-service-demo:
    name: Upgrade App Service Demo
    needs: setupcheck
    strategy:
      fail-fast: false
      matrix:
        sampleName: ['AppServiceDemo']
        configuration: ['Debug', 'Release']
        platform: ['x86', 'x64', 'ARM64']
        reactNativeWindowsVersion: [latest, preview, canary]
    uses: ./.github/workflows/template-upgradesample.yml
    with:
      sampleName:  ${{ matrix.sampleName }}
      reactNativeWindowsVersion: ${{ matrix.reactNativeWindowsVersion }}
      configuration: ${{ matrix.configuration }}
      extraRunWindowsArgs: --no-deploy
      platform: ${{ matrix.platform }}

  call-upgradesample-calculator:
    name: Upgrade Calculator
    needs: setupcheck
    strategy:
      fail-fast: false
      matrix:
        sampleName: ['Calculator\cppwinrt', 'Calculator\csharp']
        configuration: ['Debug', 'Release']
        platform: ['x86', 'x64', 'ARM64']
        reactNativeWindowsVersion: [latest, preview, canary]
    uses: ./.github/workflows/template-upgradesample.yml
    with:
      sampleName:  ${{ matrix.sampleName }}
      reactNativeWindowsVersion: ${{ matrix.reactNativeWindowsVersion }}
      configuration: ${{ matrix.configuration }}
      platform: ${{ matrix.platform }}
      runInitWindows: true
      extraInitWindowsArgs: --language ${{ endsWith(matrix.sampleName, 'cppwinrt') && 'cpp' || 'cs' }}

  call-upgradesample-calculator-nuget:
    name: Upgrade Calculator NuGet
    needs: setupcheck
    strategy:
      fail-fast: false
      matrix:
        sampleName: ['CalculatorNuGet']
        configuration: ['Debug', 'Release']
        platform: ['x86', 'x64', 'ARM64']
        reactNativeWindowsVersion: [latest, preview, canary]
    uses: ./.github/workflows/template-upgradesample.yml
    with:
      sampleName:  ${{ matrix.sampleName }}
      reactNativeWindowsVersion: ${{ matrix.reactNativeWindowsVersion }}
      configuration: ${{ matrix.configuration }}
      platform: ${{ matrix.platform }}
      runInitWindows: true
      extraInitWindowsArgs: --experimentalNuGetDependency true

  call-upgradesample-calculator-coreapp-nuget:
    name: Upgrade Calculator CoreApp NuGet
    needs: setupcheck
    strategy:
      fail-fast: false
      matrix:
        sampleName: ['CalculatorCoreAppNuGet']
        configuration: ['Debug']
        platform: ['x86']
        reactNativeWindowsVersion: [latest, preview, canary]
    uses: ./.github/workflows/template-upgradesample.yml
    with:
      sampleName:  ${{ matrix.sampleName }}
      reactNativeWindowsVersion: ${{ matrix.reactNativeWindowsVersion }}
      configuration: ${{ matrix.configuration }}
      platform: ${{ matrix.platform }}

  call-upgradesample-native-module-sample:
    name: Upgrade Native Module Sample
    needs: setupcheck
    strategy:
      fail-fast: false
      matrix:
        sampleName: ['NativeModuleSample\cppwinrt', 'NativeModuleSample\csharp']
        configuration: ['Debug', 'Release']
        platform: ['x86', 'x64', 'ARM64']
        reactNativeWindowsVersion: [latest, preview, canary]
    uses: ./.github/workflows/template-upgradesample.yml
    with:
      sampleName:  ${{ matrix.sampleName }}
      reactNativeWindowsVersion: ${{ matrix.reactNativeWindowsVersion }}
      configuration: ${{ matrix.configuration }}
      platform: ${{ matrix.platform }}
      extraRunWindowsArgs: --no-autolink --no-deploy
      # runCodeGenCheck: true # Enable once we get https://github.com/microsoft/react-native-windows/pull/11187 (Maybe 0.72?)
