# This is a basic workflow to help you get started with Actions

name: Samples CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, CI ]
  pull_request:
    branches: [ master, CI ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install VS deps
        run: Invoke-Expression "$env:GITHUB_WORKSPACE\.github\workflows\Install-VsFeatures.ps1 -Components Microsoft.Component.MSBuild,Microsoft.VisualStudio.ComponentGroup.UWP.VC,Microsoft.VisualStudio.Component.VC.Tools.x86.x64,Microsoft.VisualStudio.Component.VC.Tools.ARM,Microsoft.VisualStudio.Component.VC.Tools.ARM64,Microsoft.VisualStudio.Component.VC.v141.x86.x64,Microsoft.VisualStudio.ComponentGroup.UWP.VC.v141,Microsoft.VisualStudio.Component.VC.v141.ARM,Microsoft.VisualStudio.Component.VC.v141.ARM64"
        shell: pwsh 
        
      # Runs a single command using the runners shell
      - name: Yarn install
        run: yarn install
        working-directory: samples/Calculator

      - name: Build x86 Debug
        run: npx react-native run-windows --no-launch --no-packager --logging
        working-directory: samples/Calculator
