name: NativeModuleSample CI

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  push:
    branches:
      - master
    paths:
      - 'samples/NativeModuleSample/**'
      - '.github/workflows/samples-NativeModuleSample-CI.yml'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        sample: [NativeModuleSample\cppwinrt, NativeModuleSample\csharp]
        architecture: [x86, x64, ARM64]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\${{ matrix.sample }}" -Destination "..\..\src"

      - name: Get starting folder size
        run: ${{github.workspace}}\.github\scripts\GetFolderSize.ps1
        working-directory: ..\..\src

      - name: Yarn install
        run: yarn install --frozen-lockfile
        working-directory: ..\..\src

      - name: Build ${{ matrix.architecture }} Debug
        if: ${{ matrix.configuration == 'Debug' }}
        run: npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --logging --arch ${{ matrix.architecture }}
        working-directory: ..\..\src

      - name: Build ${{ matrix.architecture }} Release
        if: ${{ matrix.configuration == 'Release' }}
        run: npx react-native run-windows --no-deploy --no-launch --no-packager --no-autolink --logging --release --arch ${{ matrix.architecture }}
        working-directory: ..\..\src

      - name: Get final folder size
        run: ${{github.workspace}}\.github\scripts\GetFolderSize.ps1
        working-directory: ..\..\src
  
