name: Calculator CI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'samples/Calculator/**'
      - '.github/workflows/samples-Calculator-CI.yml'

jobs:
  build:
    name: CI Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Relocate to reduce long paths
        run:  Copy-item -Force -Recurse -Verbose "samples\Calculator" -Destination "..\..\src"

      - name: Yarn install
        run: yarn install
        working-directory: ..\..\src

      - name: Build x86 Debug
        run: npx react-native run-windows --no-launch --no-packager --logging
        working-directory: ..\..\src
