name: RNW Website PR

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/website-ci.yml'
      - '.github/workflows/website-pr.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  website_pr:
    name: Website PR
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Spell-check docs
      run: npx markdown-spellcheck "docs\*.md" --en-us --ignore-acronyms --ignore-numbers --report
    - name: Check for Broken Links (Docs)
      run: npx unbroken
      working-directory: ./docs
    - name: Check for Broken Links (Website)
      if: success() || failure()
      run: npx unbroken
      working-directory: ./website
    - name: Yarn Install (Website)
      if: success() || failure()
      run: yarn install --frozen-lockfile
      working-directory: ./website
    - name: Yarn Build (Website)
      run: yarn build
      working-directory: ./website
