name: RNW Website CI

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/website-ci.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  website_ci:
    name: Website CI
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Check for Broken Links (Docs)
      run: npx unbroken
      working-directory: ./docs
    - name: Check for Broken Links (Website)
      if: success() || failure()
      run: npx unbroken
      working-directory: ./website
    - name: Yarn Install (Website)
      run: yarn install --frozen-lockfile
      working-directory: ./website
    - name: Yarn Build (Website)
      run: yarn build
      working-directory: ./website
